apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: ms-notification-service
  name: ms-notification-service
spec:
  containers:
    - env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eureka-server:8888/eureka
        - name: profile
          value: default
        - name: spring.datasource.password
          value: password
        - name: spring.datasource.url
          value: jdbc:mysql://mysql:3306/notifications
      image: madd47emz/wathaequi:ms-citizen-notification
      name: ms-notification-service
      resources: {}
  restartPolicy: OnFailure
status: {}
